#!/usr/bin bash

# Using the software AdapterRemoval in default mode (--collapse  to trim and filter the fastq files generated by an Illumina Miseq
# debugging command
set -uex

# Set variables for calling forward and reverse fastq files inside the while loop
var1="_R1_001.fastq.gz"
var2="_R2_001.fastq.gz"
folder_path="/path/to/folder/with/rawreads/"
file_list="/path/to/list_of_files.txt"

# Create a folder in which to store results
mkdir Trimmed

# Activate environment with AdapterRemoval binary and enter loop around each file
source activate preprocessing-2020.3
while read -r i; do
  mkdir Trimmed/$i
  AdapterRemoval --collapse --basename Trimmed/$i/$i --file1 $folder_path/$i$var1 --file2 $folder_path/$i$var2
done < $file_list

